[package]
name = "SimpleRestaurantApi"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
rand = "0.8.5"
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
